type: dataset
id: 6
name: 0006_dataset
path: /home/fboehning/fboehning/cluster_lab/datasets/0006_dataset
parent_dir_path: /home/fboehning/fboehning/cluster_lab/datasets
parent_lab_path: /home/fboehning/fboehning/cluster_lab
timestamp_init: 2024-11-26_16-41-51
emb_model_config:
  type: emb_model
  id: 5
  name: 0005_emb_model
  path: /home/fboehning/fboehning/cluster_lab/emb_models/0005_emb_model
  parent_dir_path: /home/fboehning/fboehning/cluster_lab/emb_models
  parent_lab_path: /home/fboehning/fboehning/cluster_lab
  name_or_path: nvidia/NV-Embed-v2
  encode_config:
    instruction: 'Instruct: Retrieve the a suitable header for the chunk.

      Chunk: '
    max_length: 32768
  timestamp_init: 2024-11-26_15-42-50
  bnb_config:
    load_in_4bit: true
    bnb_4bit_use_double_quant: true
    bnb_4bit_quant_type: nf4
  model_load_config:
    trust_remote_code: true
  dir_name: emb_models
  lab_name: injection_lab
  rel_path: injection_lab/emb_models/0005_emb_model
parent_config:
  type: dataset
  id: 1
  name: 0001_dataset
  path: /home/fboehning/fboehning/cluster_lab/datasets/0001_dataset
  parent_dir_path: /home/fboehning/fboehning/cluster_lab/datasets
  parent_lab_path: /home/fboehning/fboehning/cluster_lab
  datetime_init: 2024-11-06 08:37:37.058916+01:00
  remarks: basic knowledge_df from wildbienen_db, no embeddings
  dir_name: datasets
  lab_name: injection_lab
  rel_path: injection_lab/datasets/0001_dataset
remarks: knowledge dataset with embeddings in subject, predicate and object variations
dir_name: datasets
lab_name: injection_lab
rel_path: injection_lab/datasets/0006_dataset
