id: 6
label: InjectionExperiment
lab_name: injection_lab
class_parts:
- FinetuningExperiment
- InjectionExperiment
module_path: beesup_llm.injection.experiment
do_eval_base_model_rag: false
do_eval_lora_model_rag: true
done: false
do_eval_base_model: false
do_eval_lora_model: true
do_train: true
test_mode: false
lora_config:
  r: 32
  lora_alpha: 3
  use_rslora: true
  target_modules: all-linear
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_L
sft_config:
  num_train_epochs: 10
  output_dir: /home/fboehning/fboehning/injection_lab/FinetuningExperiment/InjectionExperiment/0006_InjectionExperiment
  auto_find_batch_size: true
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 1
  learning_rate: 0.0002
  optim: paged_adamw_8bit
  save_strategy: 'no'
  save_total_limit: 1
  eval_strategy: 'no'
  logging_strategy: steps
  logging_steps: 1
  logging_first_step: true
  do_train: true
  do_eval: false
  report_to: none
  max_seq_length: 4096
  packing: false
  prediction_loss_only: false
  remove_unused_columns: false
  seed: 42
evaluators:
- class_parts:
  - LLMEvaluator
  - InjectionEvaluator
  - MCQEvaluator
  module_path: beesup_llm.injection.evaluation
  id: 3
  label: BEES
  lab_name: injection_lab
  eval_df:
    filename: eval_df.pkl
    type: DataFrame
    columns: sidx, kidx, add_kidc, add_tidc, emb_col, question, choices, answer, question_emb
    n_rows: 1000
    overwrite: false
- class_parts:
  - LLMEvaluator
  - InjectionEvaluator
  - MCQEvaluator
  module_path: beesup_llm.injection.evaluation
  id: 4
  label: MMLU
  lab_name: injection_lab
  eval_df:
    filename: eval_df.pkl
    type: DataFrame
    columns: mmluidx, question, subject, choices, answer, question_emb
    n_rows: 1000
    overwrite: false
- class_parts:
  - LLMEvaluator
  - InjectionEvaluator
  - QDQEvaluator
  module_path: beesup_llm.injection.evaluation
  id: 1
  label: QDQEvaluator
  lab_name: injection_lab
  n_fewshots: 3
  eval_df:
    filename: eval_df.pkl
    type: DataFrame
    columns: question, target_attr, gold_items, question_emb
    n_rows: 30
    overwrite: false
- class_parts:
  - LLMEvaluator
  - InjectionEvaluator
  - FFQEvaluator
  module_path: beesup_llm.injection.evaluation
  id: 1
  label: BEES
  lab_name: injection_lab
  eval_df:
    filename: eval_df.pkl
    type: DataFrame
    columns: sidx, kidx, tidx, add_kidc, emb_col, question, answer, question_emb
    n_rows: 5
    overwrite: false
toc: " Wildbienen\n\u251C\u2500\u2500  Gef\xE4hrdete Wildbienenarten\n\u2502   \u251C\
  \u2500\u2500  Umgangssprachliche Bezeichnungen gef\xE4hrdeter Wildbienenarten\n\u2502\
  \   \u2514\u2500\u2500  Gef\xE4hrdete Wildbienenarten mit besonderen Wirtsbienen\
  \ und Kuckuckswespen\n\u2502       \u251C\u2500\u2500  Familien der Wildbienen\n\
  \u2502       \u2514\u2500\u2500  Gef\xE4hrdete Wildbienenarten mit besonderen Wirtsbienen\
  \ und Kuckuckswespen aus bestimmten Familien\n\u2502           \u251C\u2500\u2500\
  \  Gef\xE4hrdung von Wildbienenarten mit bestimmten Lebensraumtypen und Pflanzen\
  \ als Pollenlieferanten\n\u2502           \u2514\u2500\u2500  Wirtsbienen und Wirte\
  \ der gef\xE4hrdeten Wildbienenarten mit besonderen Kuckuckswespen\n\u2502     \
  \          \u251C\u2500\u2500  Kuckuckswespen der gef\xE4hrdeten Wildbienenarten\n\
  \u2502               \u251C\u2500\u2500  Wirtsbienen der gef\xE4hrdeten Wildbienenarten\
  \ mit besonderen Kuckuckswespen\n\u2502               \u2514\u2500\u2500  Wirtsbienen\
  \ und Wirte der gef\xE4hrdeten Wildbienenarten mit besonderen Kuckuckswespen aus\
  \ bestimmten Familien: Furchenbienen und Sandbienen\n\u251C\u2500\u2500  Merkmale\
  \ und Lebensweise von S. ephippius\n\u2502   \u251C\u2500\u2500  Morphologische\
  \ Merkmale von S. ephippius\n\u2502   \u2514\u2500\u2500  Pollenquellen und Lebensraum\
  \ von S. ephippius\n\u2502       \u251C\u2500\u2500  Pollenquellen und Nahrungspr\xE4\
  ferenzen von S. ephippius\n\u2502       \u251C\u2500\u2500  Vorkommen und Lebensweise\
  \ in Europa\n\u2502       \u2514\u2500\u2500  Habitatverbreitung von Wildbienen-Arten\n\
  \u2514\u2500\u2500  Nist- und Bauverhalten\n    \u251C\u2500\u2500  Nistpl\xE4tze:\
  \ Hohlr\xE4ume und Insektenfra\xDFg\xE4nge\n    \u251C\u2500\u2500  Pollensammelverhalten:\
  \ Artenvielfalt und Pr\xE4ferenzen\n    \u251C\u2500\u2500  Sozialverhalten\n  \
  \  \u2514\u2500\u2500  Baumaterialien und Requisiten f\xFCr die Nestherstellung\n\
  \        \u251C\u2500\u2500  Baumaterialien f\xFCr die Nestherstellung\n       \
  \ \u2514\u2500\u2500  Requisiten: Fels- und Steinelemente\n"
timestamp_start: 2025-03-26_03-21-44
lora_info:
  n_trainable_params: 83886080
  n_total_params: 8114147328
  p_trainable_params: 0.010338249554642546
  lora_scale: 0.5303300858899106
data_df:
  class_parts:
  - Datahandle
  - InjectionDatahandle
  module_path: labtools.datahandle
  id: 3
  label: InjectionDatahandle
  lab_name: injection_lab
  remarks: english system prompt, german query prompt
  use_taxonomy: true
  taxomizer:
    id: 3
    label: Taxomizer
    lab_name: injection_lab
    class_parts:
    - Taxomizer
    module_path: beesup_llm.injection.taxomizing
    chunk_txt_template: '{p}: {o}'
    chunk_txt_key: txt
    chunk_emb_key: emb
    linkage_args:
      method: ward
    dist_flattening_config:
      include_leaves: false
      use_kneepoint: true
      use_std: false
    ddist_flattening_config:
      include_leaves: false
      use_kneepoint: true
      use_std: false
    tree_info:
      bin_tree:
        num_inodes: 3411
        num_leaves: 3412
        num_inodes_per_depth:
        - 2
        - 4
        - 8
        - 16
        - 30
        - 56
        - 96
        - 160
        - 227
        - 286
        - 316
        - 314
        - 284
        - 221
        - 172
        - 125
        - 103
        - 76
        - 62
        - 52
        - 50
        - 45
        - 42
        - 37
        - 39
        - 40
        - 39
        - 37
        - 32
        - 27
        - 24
        - 23
        - 23
        - 21
        - 20
        - 16
        - 12
        - 8
        - 7
        - 7
        - 6
        - 6
        - 5
        - 5
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 2
        - 2
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 0
        num_leaves_per_depth:
        - 0
        - 0
        - 0
        - 0
        - 2
        - 4
        - 16
        - 32
        - 93
        - 168
        - 256
        - 318
        - 344
        - 347
        - 270
        - 219
        - 147
        - 130
        - 90
        - 72
        - 54
        - 55
        - 48
        - 47
        - 35
        - 38
        - 41
        - 41
        - 42
        - 37
        - 30
        - 25
        - 23
        - 25
        - 22
        - 24
        - 20
        - 16
        - 9
        - 7
        - 8
        - 6
        - 7
        - 5
        - 6
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 4
        - 5
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 3
        - 4
        - 2
        - 3
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 1
        - 2
        height: 121
        avg_depth: 20.1237
        width: 632
        dia: 231
        branching: 2.0
        avg_degree: 0.9999
        avg_balance: 4.3579
      dist_threshold: 0.8682037974909939
      dist_tree:
        num_inodes: 54
        num_leaves: 3412
        num_inodes_per_depth:
        - 2
        - 4
        - 7
        - 9
        - 11
        - 15
        - 3
        - 2
        - 0
        num_leaves_per_depth:
        - 0
        - 0
        - 35
        - 862
        - 771
        - 325
        - 1194
        - 129
        - 96
        height: 9
        avg_depth: 5.7302
        width: 1197
        dia: 18
        branching: 65.3396
        avg_degree: 0.9997
        avg_balance: 0.0147
      ddist_threshold: 2.1417767549697544
      ddist_tree_raw:
        num_inodes: 23
        num_leaves: 3412
        num_inodes_per_depth:
        - 3
        - 8
        - 7
        - 2
        - 2
        - 0
        num_leaves_per_depth:
        - 0
        - 0
        - 1640
        - 1064
        - 559
        - 149
        height: 6
        avg_depth: 3.7622
        width: 1647
        dia: 10
        branching: 155.9545
        avg_degree: 0.9997
        avg_balance: 0.0032
      ddist_tree_rec:
        num_inodes: 24
        num_leaves: 3412
        num_inodes_per_depth:
        - 3
        - 8
        - 7
        - 2
        - 3
        - 0
        num_leaves_per_depth:
        - 0
        - 0
        - 1640
        - 1064
        - 318
        - 390
        height: 6
        avg_depth: 3.8327
        width: 1647
        dia: 10
        branching: 149.2174
        avg_degree: 0.9997
        avg_balance: 0.0029
    chunks_df:
      filename: chunks_df.pkl
      type: DataFrame
      columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb,
        label, txt, n_tokens
      n_rows: 3412
      overwrite: false
      id: 2
      label: ChunksDatahandle
      lab_name: injection_lab
      class_parts:
      - Datahandle
      - ChunksDatahandle
      module_path: labtools.datahandle
      remarks: 'emb = po_emb, excluded rows with p="Wissenschaftlicher Name" '
      drop_emb_duplicates: false
      emb_dh:
        id: 2
        label: EmbeddingDatahandle
        lab_name: injection_lab
        class_parts:
        - Datahandle
        - EmbeddingDatahandle
        module_path: labtools.datahandle
        emb_templates:
          s: '{s}'
          p: '{p}'
          o: '{o}'
          spo: '{s}


            {p}


            {o}'
          po: '{p}


            {o}'
          so: '{s}


            {o}'
        base_dh:
          id: 1
          label: wildbienen_database
          lab_name: injection_lab
          class_parts:
          - Datahandle
          - BaseDatahandle
          module_path: labtools.datahandle
        emb_pipe_config:
          id: 1
          label: NVEmbedPipeline
          lab_name: injection_lab
          class_parts:
          - EMBPipeline
          - NVEmbedPipeline
          module_path: beesup_llm.emb
          name_or_path: nvidia/NV-Embed-v2
          instruction: 'Instruct: Given a passage, retrieve a suitable header



            Passage:


            '
      data_df:
        filename: data_df.pkl
        type: DataFrame
        columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb,
          label
        n_rows: 3412
        overwrite: false
    llm_pipe:
      class_parts:
      - LLMPipeline
      - LlamaPipeline
      module_path: beesup_llm.llm
      label: LlamaPipeline
      lab_name: injection_lab
      name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
      generation_config:
        return_dict_in_generate: false
        max_time: 1200
        do_sample: false
        stop_strings:
        - '

          '
        max_new_tokens: 100
        pad_token: <|begin_of_text|>
        pad_token_id: 128000
      inference_tokenizer_config:
        padding: longest
        padding_side: left
        max_length: 8192
        pad_token: <|begin_of_text|>
        pad_token_id: 128000
      training_tokenizer_config:
        padding: longest
        padding_side: right
        max_length: 8192
        pad_token: <|end_of_text|>
        pad_token_id: 128001
      pipeline_args:
        return_full_text: false
        clean_up_tokenization_spaces: true
    linkage_matrix:
      filename: linkage_matrix.pkl
      type: ndarray
      shape: (3411, 4)
      dtype: float64
    bin_tree:
      filename: bin_tree.pkl
      type: Node
      size: 6823
      height: 121
    dist_tree:
      filename: dist_tree.pkl
      type: Node
      size: 3466
      height: 9
    ddist_tree:
      filename: ddist_tree.pkl
      type: Node
      size: 3436
      height: 6
    emb_tree:
      filename: emb_tree.pkl
      type: Node
      size: 3436
      height: 6
    llm_tree:
      filename: llm_tree.pkl
      type: Node
      size: 3436
      height: 6
  data_df:
    filename: data_df.pkl
    type: DataFrame
    columns: kidx, tidx, prompt_messages, gold_message, toc, toc_until, node_id, hpath,
      split
    n_rows: 3412
    overwrite: false
llm_pipe:
  class_parts:
  - LLMPipeline
  - LlamaPipeline
  module_path: beesup_llm.llm
  label: LlamaPipeline
  lab_name: injection_lab
  name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
  generation_config:
    return_dict_in_generate: false
    max_time: 1200
    do_sample: false
    max_new_tokens: 4096
    pad_token: <|begin_of_text|>
    pad_token_id: 128000
  inference_tokenizer_config:
    padding: longest
    padding_side: left
    max_length: 8192
    pad_token: <|begin_of_text|>
    pad_token_id: 128000
  training_tokenizer_config:
    padding: longest
    padding_side: right
    max_length: 8192
    pad_token: <|end_of_text|>
    pad_token_id: 128001
  pipeline_args:
    return_full_text: false
    clean_up_tokenization_spaces: true
rag_pipe:
  class_parts:
  - RAGPipeline
  module_path: beesup_llm.rag
  label: RAGPipeline
  lab_name: injection_lab
  chunk_txt_key: spo
  chunk_emb_key: emb
  chunk_instruction: ''
  query_txt_key: question
  query_emb_key: question_emb
  query_instruction: Given a question, retrieve passages that answer the question
  limiters:
  - class_parts:
    - RAGLimiter
    - NumLimiter
    module_path: beesup_llm.rag
    limit: 100
  - class_parts:
    - RAGLimiter
    - TokenLimiter
    module_path: beesup_llm.rag
    limit: 1000
  - class_parts:
    - RAGLimiter
    - KneeLimiter
    module_path: beesup_llm.rag
    curve: convex
    direction: decreasing
  chunks_df:
    class_parts:
    - Datahandle
    - ChunksDatahandle
    module_path: labtools.datahandle
    id: 3
    label: RAG_CHUNKS
    lab_name: injection_lab
    remarks: 'emb = spo_emb, excluded rows with p="Wissenschaftlicher Name" '
    emb_pipe:
      id: 1
      label: NVEmbedPipeline
      lab_name: injection_lab
      class_parts:
      - EMBPipeline
      - NVEmbedPipeline
      module_path: beesup_llm.emb
      name_or_path: nvidia/NV-Embed-v2
      instruction: ''
    data_df:
      filename: data_df.pkl
      type: DataFrame
      columns: spo, s, p, o, source_name, attr_type, n_units, n_words, emb
      n_rows: 3412
      overwrite: false
