type: rag_pipeline
id: 2
name: 0002_rag_pipeline
dir_name: rag_pipelines
lab_name: injection_lab
rel_path: injection_lab/rag_pipelines/0002_rag_pipeline
emb_col: spo
chunk_col: spo
llm_config:
  generation_config:
    max_new_tokens: 4096
    max_time: 1200
timestamp_init: 2025-02-25_15-40-54
pre_trim_limit:
  limit: 100
fit_tokn_limit:
  limit: 1000
fit_knee_score:
  curve: convex
  direction: decreasing
