id: 34
label: Taxomizer
lab_name: injection_lab
class_parts:
- Taxomizer
module_path: beesup_llm.injection.taxomizing
chunk_txt_template: '{p}: {o}'
chunk_txt_key: txt
chunk_emb_key: emb
linkage_args:
  method: average
  optimal_ordering: false
dist_flattening_config:
  include_leaves: false
  use_kneepoint: false
  use_std: true
  std_factor: 1.0
ddist_flattening_config:
  include_leaves: false
  use_kneepoint: false
  use_std: true
  std_factor: 1.0
tree_info:
  bin_tree:
    num_inodes: 3411
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 8
    - 14
    - 20
    - 28
    - 38
    - 46
    - 50
    - 61
    - 62
    - 73
    - 73
    - 66
    - 69
    - 82
    - 80
    - 75
    - 78
    - 80
    - 75
    - 83
    - 78
    - 86
    - 83
    - 82
    - 71
    - 65
    - 57
    - 49
    - 45
    - 41
    - 36
    - 38
    - 41
    - 37
    - 39
    - 40
    - 37
    - 38
    - 35
    - 34
    - 28
    - 25
    - 26
    - 25
    - 25
    - 23
    - 22
    - 23
    - 27
    - 29
    - 27
    - 29
    - 27
    - 30
    - 23
    - 23
    - 18
    - 17
    - 13
    - 14
    - 12
    - 13
    - 11
    - 10
    - 10
    - 12
    - 9
    - 10
    - 10
    - 9
    - 9
    - 10
    - 11
    - 12
    - 16
    - 11
    - 13
    - 10
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 5
    - 5
    - 5
    - 5
    - 4
    - 4
    - 3
    - 3
    - 3
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 2
    - 8
    - 12
    - 18
    - 30
    - 42
    - 39
    - 60
    - 51
    - 73
    - 80
    - 63
    - 56
    - 84
    - 85
    - 72
    - 76
    - 85
    - 67
    - 88
    - 70
    - 89
    - 84
    - 93
    - 77
    - 73
    - 65
    - 53
    - 49
    - 46
    - 34
    - 35
    - 45
    - 35
    - 38
    - 43
    - 36
    - 41
    - 36
    - 40
    - 31
    - 24
    - 27
    - 25
    - 27
    - 24
    - 21
    - 19
    - 25
    - 31
    - 25
    - 31
    - 24
    - 37
    - 23
    - 28
    - 19
    - 21
    - 12
    - 16
    - 11
    - 15
    - 12
    - 10
    - 8
    - 15
    - 8
    - 10
    - 11
    - 9
    - 8
    - 9
    - 10
    - 8
    - 21
    - 9
    - 16
    - 12
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 9
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 8
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 7
    - 5
    - 5
    - 5
    - 6
    - 4
    - 5
    - 3
    - 3
    - 4
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 3
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    height: 244
    avg_depth: 47.2097
    width: 172
    dia: 445
    branching: 2.0
    avg_degree: 0.9999
    avg_balance: 14.4881
  dist_threshold: 0.10521982889035114
  dist_tree:
    num_inodes: 1168
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 8
    - 11
    - 11
    - 18
    - 24
    - 27
    - 28
    - 35
    - 40
    - 44
    - 43
    - 40
    - 44
    - 56
    - 54
    - 46
    - 47
    - 53
    - 47
    - 51
    - 47
    - 51
    - 39
    - 33
    - 30
    - 31
    - 24
    - 20
    - 14
    - 11
    - 10
    - 10
    - 11
    - 11
    - 11
    - 10
    - 9
    - 9
    - 5
    - 6
    - 4
    - 5
    - 4
    - 4
    - 3
    - 2
    - 3
    - 5
    - 4
    - 3
    - 3
    - 1
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 30
    - 51
    - 23
    - 324
    - 166
    - 59
    - 382
    - 31
    - 89
    - 47
    - 91
    - 156
    - 142
    - 176
    - 180
    - 52
    - 48
    - 69
    - 58
    - 73
    - 83
    - 114
    - 94
    - 55
    - 45
    - 41
    - 52
    - 34
    - 41
    - 39
    - 48
    - 17
    - 17
    - 23
    - 23
    - 32
    - 37
    - 73
    - 47
    - 19
    - 6
    - 78
    - 5
    - 12
    - 4
    - 1
    - 1
    - 12
    - 96
    - 3
    - 7
    - 1
    - 5
    height: 56
    avg_depth: 20.479
    width: 417
    dia: 104
    branching: 3.922
    avg_degree: 0.9998
    avg_balance: 1.1725
  ddist_threshold: 0.030064453388028798
  ddist_tree_raw:
    num_inodes: 634
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 9
    - 13
    - 19
    - 29
    - 43
    - 70
    - 98
    - 138
    - 113
    - 70
    - 21
    - 4
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 64
    - 44
    - 362
    - 208
    - 170
    - 647
    - 398
    - 678
    - 390
    - 351
    - 76
    - 24
    height: 15
    avg_depth: 9.7096
    width: 791
    dia: 25
    branching: 6.387
    avg_degree: 0.9998
    avg_balance: 0.176
  ddist_tree_rec:
    num_inodes: 902
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 9
    - 16
    - 25
    - 40
    - 55
    - 94
    - 134
    - 199
    - 173
    - 109
    - 35
    - 6
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 40
    - 30
    - 305
    - 138
    - 248
    - 459
    - 548
    - 449
    - 629
    - 406
    - 134
    - 26
    height: 15
    avg_depth: 10.0327
    width: 747
    dia: 25
    branching: 4.7847
    avg_degree: 0.9998
    avg_balance: 0.1029
chunks_df:
  filename: chunks_df.pkl
  type: DataFrame
  columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label,
    txt, node_id
  n_rows: 3412
  overwrite: false
  id: 2
  label: ChunksDatahandle
  lab_name: injection_lab
  class_parts:
  - Datahandle
  - ChunksDatahandle
  module_path: labtools.datahandle
  remarks: 'emb = po_emb, excluded rows with p="Wissenschaftlicher Name" '
  drop_emb_duplicates: false
  emb_dh:
    id: 2
    label: EmbeddingDatahandle
    lab_name: injection_lab
    class_parts:
    - Datahandle
    - EmbeddingDatahandle
    module_path: labtools.datahandle
    emb_templates:
      s: '{s}'
      p: '{p}'
      o: '{o}'
      spo: '{s}


        {p}


        {o}'
      po: '{p}


        {o}'
      so: '{s}


        {o}'
    base_dh:
      id: 1
      label: wildbienen_database
      lab_name: injection_lab
      class_parts:
      - Datahandle
      - BaseDatahandle
      module_path: labtools.datahandle
    emb_pipe_config:
      id: 1
      label: NVEmbedPipeline
      lab_name: injection_lab
      class_parts:
      - EMBPipeline
      - NVEmbedPipeline
      module_path: beesup_llm.emb
      name_or_path: nvidia/NV-Embed-v2
      instruction: 'Instruct: Given a passage, retrieve a suitable header



        Passage:


        '
  data_df:
    filename: data_df.pkl
    type: DataFrame
    columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label
    n_rows: 3412
    overwrite: false
linkage_matrix:
  filename: linkage_matrix.pkl
  type: ndarray
  shape: (3411, 4)
  dtype: float64
bin_tree:
  filename: bin_tree.pkl
  type: Node
  size: 6823
  height: 244
dist_tree:
  filename: dist_tree.pkl
  type: Node
  size: 4580
  height: 56
ddist_tree:
  filename: ddist_tree.pkl
  type: Node
  size: 4314
  height: 15
emb_tree:
  filename: emb_tree.pkl
  type: Node
  size: 4314
  height: 15
llm_tree:
  filename: llm_tree.pkl
  type: NoneType
