id: 5
label: InjectionDatahandle
lab_name: injection_lab
class_parts:
- Datahandle
- InjectionDatahandle
module_path: labtools.datahandle
remarks: english system prompt, german query prompt
use_taxonomy: true
taxomizer:
  id: 5
  label: Taxomizer
  lab_name: injection_lab
  class_parts:
  - Taxomizer
  module_path: beesup_llm.injection.taxomizing
  chunk_txt_template: '{p}: {o}'
  chunk_txt_key: txt
  chunk_emb_key: emb
  linkage_args:
    method: ward
    optimal_ordering: false
  dist_flattening_config:
    include_leaves: false
    use_kneepoint: true
    use_std: false
    std_factor: 1.0
  ddist_flattening_config:
    include_leaves: false
    use_kneepoint: true
    use_std: false
    std_factor: 1.0
  tree_info:
    bin_tree:
      num_inodes: 3411
      num_leaves: 3412
      num_inodes_per_depth:
      - 2
      - 4
      - 8
      - 16
      - 31
      - 55
      - 82
      - 121
      - 151
      - 168
      - 190
      - 199
      - 219
      - 218
      - 188
      - 142
      - 112
      - 90
      - 76
      - 63
      - 58
      - 58
      - 46
      - 38
      - 26
      - 26
      - 21
      - 24
      - 23
      - 19
      - 13
      - 11
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 9
      - 9
      - 9
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 6
      - 5
      - 5
      - 5
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      - 3
      - 3
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 0
      num_leaves_per_depth:
      - 0
      - 0
      - 0
      - 0
      - 1
      - 7
      - 28
      - 43
      - 91
      - 134
      - 146
      - 181
      - 179
      - 220
      - 248
      - 234
      - 172
      - 134
      - 104
      - 89
      - 68
      - 58
      - 70
      - 54
      - 50
      - 26
      - 31
      - 18
      - 25
      - 27
      - 25
      - 15
      - 12
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 10
      - 11
      - 9
      - 9
      - 10
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 8
      - 9
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 7
      - 8
      - 7
      - 5
      - 5
      - 6
      - 4
      - 4
      - 4
      - 4
      - 4
      - 4
      - 5
      - 3
      - 4
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 2
      - 3
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 1
      - 2
      height: 245
      avg_depth: 37.4454
      width: 438
      dia: 452
      branching: 2.0
      avg_degree: 0.9999
      avg_balance: 13.5788
    dist_threshold: 0.4092860817909241
    dist_tree:
      num_inodes: 86
      num_leaves: 3412
      num_inodes_per_depth:
      - 2
      - 4
      - 8
      - 11
      - 15
      - 16
      - 15
      - 10
      - 3
      - 1
      - 0
      num_leaves_per_depth:
      - 0
      - 0
      - 0
      - 1198
      - 505
      - 363
      - 768
      - 170
      - 323
      - 47
      - 38
      height: 11
      avg_depth: 5.8596
      width: 1209
      dia: 19
      branching: 41.1176
      avg_degree: 0.9997
      avg_balance: 0.0234
    ddist_threshold: 0.09939849376678467
    ddist_tree_raw:
      num_inodes: 34
      num_leaves: 3412
      num_inodes_per_depth:
      - 2
      - 16
      - 15
      - 0
      num_leaves_per_depth:
      - 0
      - 511
      - 2492
      - 409
      height: 4
      avg_depth: 2.9637
      width: 2507
      dia: 8
      branching: 104.3333
      avg_degree: 0.9997
      avg_balance: 0.0038
    ddist_tree_rec:
      num_inodes: 45
      num_leaves: 3412
      num_inodes_per_depth:
      - 2
      - 17
      - 25
      - 0
      num_leaves_per_depth:
      - 0
      - 0
      - 1874
      - 1538
      height: 4
      avg_depth: 3.438
      width: 1899
      dia: 8
      branching: 78.5
      avg_degree: 0.9997
      avg_balance: 0.0006
  chunks_df:
    filename: chunks_df.pkl
    type: DataFrame
    columns: tidx, kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb,
      label, txt, n_tokens, node_id, toc, toc_until, hpath, prompt_messages, gold_message
    n_rows: 3412
    overwrite: false
  llm_pipe:
    class_parts:
    - LLMPipeline
    - LlamaPipeline
    module_path: beesup_llm.llm
    label: LlamaPipeline
    lab_name: injection_lab
    name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
    generation_config:
      return_dict_in_generate: false
      max_time: 1200
      do_sample: false
      stop_strings:
      - '

        '
      max_new_tokens: 100
      pad_token: <|begin_of_text|>
      pad_token_id: 128000
    inference_tokenizer_config:
      padding: longest
      padding_side: left
      max_length: 8192
      pad_token: <|begin_of_text|>
      pad_token_id: 128000
    training_tokenizer_config:
      padding: longest
      padding_side: right
      max_length: 8192
      pad_token: <|end_of_text|>
      pad_token_id: 128001
    pipeline_args:
      return_full_text: false
      clean_up_tokenization_spaces: true
  linkage_matrix:
    filename: linkage_matrix.pkl
    type: ndarray
    shape: (3411, 4)
    dtype: float64
  bin_tree:
    filename: bin_tree.pkl
    type: Node
    size: 6823
    height: 245
  dist_tree:
    filename: dist_tree.pkl
    type: Node
    size: 3498
    height: 11
  ddist_tree:
    filename: ddist_tree.pkl
    type: Node
    size: 3457
    height: 4
  emb_tree:
    filename: emb_tree.pkl
    type: Node
    size: 3457
    height: 4
  llm_tree:
    filename: llm_tree.pkl
    type: Node
    size: 3457
    height: 4
data_df:
  type: DataFrame
  filename: data_df.pkl
  n_rows: 3412
  columns: kidx, tidx, prompt_messages, gold_message, toc, toc_until, node_id, hpath,
    split
  overwrite: false
