id: 3
label: knowledge_triples
lab_name: injection_lab
class_parts:
- Datahandle
module_path: labtools.data
n_rows: 3412
columns:
- s
- p
- o
- source_name
- attr_type
- n_units
- n_words
- s_emb
- p_emb
- o_emb
- spo
- spo_emb
- po
- po_emb
- so
- so_emb
