id: 1
label: bees
lab_name: injection_lab
class_parts:
- Evaluator
- FFQEvaluator
module_path: beesup_llm.injection.evaluation
eval_df:
  type: DataFrame
  filename: eval_df.pkl
  n_rows: 5
  columns: sidx, kidx, tidx, add_kidc, emb_col, question, answer, question_emb
  overwrite: false
