id: 51
label: Taxomizer
lab_name: injection_lab
class_parts:
- Taxomizer
module_path: beesup_llm.injection.taxomizing
chunk_txt_template: '{p}: {o}'
chunk_txt_key: txt
chunk_emb_key: emb
linkage_args:
  method: average
  optimal_ordering: false
dist_flattening_config:
  include_leaves: false
  use_kneepoint: false
  use_std: true
  std_factor: 2.6
ddist_flattening_config:
  include_leaves: false
  use_kneepoint: false
  use_std: true
  std_factor: 2.6
tree_info:
  bin_tree:
    num_inodes: 3411
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 8
    - 14
    - 20
    - 28
    - 38
    - 46
    - 50
    - 61
    - 62
    - 73
    - 73
    - 66
    - 69
    - 82
    - 80
    - 75
    - 78
    - 80
    - 75
    - 83
    - 78
    - 86
    - 83
    - 82
    - 71
    - 65
    - 57
    - 49
    - 45
    - 41
    - 36
    - 38
    - 41
    - 37
    - 39
    - 40
    - 37
    - 38
    - 35
    - 34
    - 28
    - 25
    - 26
    - 25
    - 25
    - 23
    - 22
    - 23
    - 27
    - 29
    - 27
    - 29
    - 27
    - 30
    - 23
    - 23
    - 18
    - 17
    - 13
    - 14
    - 12
    - 13
    - 11
    - 10
    - 10
    - 12
    - 9
    - 10
    - 10
    - 9
    - 9
    - 10
    - 11
    - 12
    - 16
    - 11
    - 13
    - 10
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 5
    - 5
    - 5
    - 5
    - 4
    - 4
    - 3
    - 3
    - 3
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 2
    - 8
    - 12
    - 18
    - 30
    - 42
    - 39
    - 60
    - 51
    - 73
    - 80
    - 63
    - 56
    - 84
    - 85
    - 72
    - 76
    - 85
    - 67
    - 88
    - 70
    - 89
    - 84
    - 93
    - 77
    - 73
    - 65
    - 53
    - 49
    - 46
    - 34
    - 35
    - 45
    - 35
    - 38
    - 43
    - 36
    - 41
    - 36
    - 40
    - 31
    - 24
    - 27
    - 25
    - 27
    - 24
    - 21
    - 19
    - 25
    - 31
    - 25
    - 31
    - 24
    - 37
    - 23
    - 28
    - 19
    - 21
    - 12
    - 16
    - 11
    - 15
    - 12
    - 10
    - 8
    - 15
    - 8
    - 10
    - 11
    - 9
    - 8
    - 9
    - 10
    - 8
    - 21
    - 9
    - 16
    - 12
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 9
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 8
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 7
    - 5
    - 5
    - 5
    - 6
    - 4
    - 5
    - 3
    - 3
    - 4
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 3
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    height: 244
    avg_depth: 47.2097
    width: 172
    dia: 445
    branching: 2.0
    avg_degree: 0.9999
    avg_balance: 14.4881
  dist_threshold: 0.273571555114913
  dist_tree:
    num_inodes: 234
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 3
    - 4
    - 7
    - 8
    - 12
    - 17
    - 19
    - 20
    - 21
    - 21
    - 22
    - 16
    - 13
    - 9
    - 8
    - 8
    - 7
    - 4
    - 2
    - 4
    - 2
    - 1
    - 1
    - 1
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 65
    - 64
    - 1
    - 365
    - 201
    - 10
    - 367
    - 28
    - 38
    - 131
    - 548
    - 906
    - 48
    - 44
    - 226
    - 16
    - 44
    - 88
    - 29
    - 0
    - 72
    - 11
    - 6
    - 3
    - 5
    - 96
    height: 27
    avg_depth: 11.6306
    width: 922
    dia: 45
    branching: 15.6352
    avg_degree: 0.9997
    avg_balance: 0.1975
  ddist_threshold: 0.07332403539129181
  ddist_tree_raw:
    num_inodes: 56
    num_leaves: 3412
    num_inodes_per_depth:
    - 12
    - 34
    - 9
    - 0
    num_leaves_per_depth:
    - 360
    - 329
    - 2288
    - 435
    height: 4
    avg_depth: 2.8054
    width: 2297
    dia: 7
    branching: 56.2727
    avg_degree: 0.9997
    avg_balance: 0.0046
  ddist_tree_rec:
    num_inodes: 69
    num_leaves: 3412
    num_inodes_per_depth:
    - 13
    - 42
    - 13
    - 0
    num_leaves_per_depth:
    - 0
    - 377
    - 1886
    - 1149
    height: 4
    avg_depth: 3.2014
    width: 1899
    dia: 7
    branching: 50.9853
    avg_degree: 0.9997
    avg_balance: 0.0009
chunks_df:
  filename: chunks_df.pkl
  type: DataFrame
  columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label,
    txt, node_id
  n_rows: 3412
  overwrite: false
  id: 2
  label: ChunksDatahandle
  lab_name: injection_lab
  class_parts:
  - Datahandle
  - ChunksDatahandle
  module_path: labtools.datahandle
  remarks: 'emb = po_emb, excluded rows with p="Wissenschaftlicher Name" '
  drop_emb_duplicates: false
  emb_dh:
    id: 2
    label: EmbeddingDatahandle
    lab_name: injection_lab
    class_parts:
    - Datahandle
    - EmbeddingDatahandle
    module_path: labtools.datahandle
    emb_templates:
      s: '{s}'
      p: '{p}'
      o: '{o}'
      spo: '{s}


        {p}


        {o}'
      po: '{p}


        {o}'
      so: '{s}


        {o}'
    base_dh:
      id: 1
      label: wildbienen_database
      lab_name: injection_lab
      class_parts:
      - Datahandle
      - BaseDatahandle
      module_path: labtools.datahandle
    emb_pipe_config:
      id: 1
      label: NVEmbedPipeline
      lab_name: injection_lab
      class_parts:
      - EMBPipeline
      - NVEmbedPipeline
      module_path: beesup_llm.emb
      name_or_path: nvidia/NV-Embed-v2
      instruction: 'Instruct: Given a passage, retrieve a suitable header



        Passage:


        '
  data_df:
    filename: data_df.pkl
    type: DataFrame
    columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label
    n_rows: 3412
    overwrite: false
linkage_matrix:
  filename: linkage_matrix.pkl
  type: ndarray
  shape: (3411, 4)
  dtype: float64
bin_tree:
  filename: bin_tree.pkl
  type: Node
  size: 6823
  height: 244
dist_tree:
  filename: dist_tree.pkl
  type: Node
  size: 3646
  height: 27
ddist_tree:
  filename: ddist_tree.pkl
  type: Node
  size: 3481
  height: 4
emb_tree:
  filename: emb_tree.pkl
  type: Node
  size: 3481
  height: 4
llm_tree:
  filename: llm_tree.pkl
  type: NoneType
