id: 1
label: LLMPipeline
lab_name: injection_lab
class_parts:
- LLMPipeline
module_path: beesup_llm.model_pipelines
name_or_path: null
generation_config:
  return_dict_in_generate: false
  max_time: 600
  do_sample: false
  stop_strings: null
  max_new_tokens: 1000
inference_tokenizer_config:
  padding: longest
  padding_side: left
training_tokenizer_config:
  padding: longest
  padding_side: right
pipeline_args:
  return_full_text: false
  clean_up_tokenization_spaces: true
