id: 2
label: some_embedding_chunks
lab_name: injection_lab
class_parts:
- Datahandle
module_path: labtools.data
remarks: just a test
n_rows: 10
columns:
- s
- p
- o
- source_name
- attr_type
- n_units
- n_words
- s_emb
- p_emb
- o_emb
- spo
- spo_emb
- po
- po_emb
- so
- so_emb
