id: 1
label: RAGPipeline
lab_name: injection_lab
class_parts:
- RAGPipeline
module_path: beesup_llm.injection.rag
chunk_txt_key: chunk
chunk_emb_key: emb
chunk_instruction: ''
query_txt_key: query
query_emb_key: emb
query_instruction: Given a question, retrieve passages that answer the question
chunks_df:
  type: DataFrame
  filename: chunks_df.pkl
  n_rows: 3412
  columns: chunk, subject, predicate, object, source_name, attr_type, n_units, n_words,
    label, emb, k_idc, node_id
  overwrite: false
llm_pipe:
  class_parts:
  - LLMPipeline
  - LlamaPipeline
  module_path: beesup_llm.llm
  id: 1
  label: LlamaPipeline
  lab_name: injection_lab
  name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
  generation_config:
    return_dict_in_generate: false
    max_time: 1200
    do_sample: false
    max_new_tokens: 4096
    pad_token: <|begin_of_text|>
    pad_token_id: 128000
  inference_tokenizer_config:
    padding: longest
    padding_side: left
    max_length: 8192
    pad_token: <|begin_of_text|>
    pad_token_id: 128000
  training_tokenizer_config:
    padding: longest
    padding_side: right
    max_length: 8192
    pad_token: <|end_of_text|>
    pad_token_id: 128001
  pipeline_args:
    return_full_text: false
    clean_up_tokenization_spaces: true
emb_pipe:
  class_parts:
  - EMBPipeline
  - NVEmbedPipeline
  module_path: beesup_llm.emb
  id: 1
  label: NVEmbedPipeline
  lab_name: injection_lab
  name_or_path: nvidia/NV-Embed-v2
  instruction: Given a question, retrieve passages that answer the question
limiters:
- class_parts:
  - RAGLimiter
  - NumLimiter
  module_path: beesup_llm.injection.rag
  name: NumLimiter
  limit: 100
- class_parts:
  - RAGLimiter
  - TokenLimiter
  module_path: beesup_llm.injection.rag
  name: TokenLimiter
  limit: 1000
- class_parts:
  - RAGLimiter
  - KneeLimiter
  module_path: beesup_llm.injection.rag
  name: KneeLimiter
  curve: convex
  direction: decreasing
