id: 1
label: RAGPipeline
lab_name: injection_lab
class_parts:
- RAGPipeline
module_path: beesup_llm.injection.rag
chunk_txt_key: spo
chunk_emb_key: emb
chunk_instruction: ''
query_txt_key: question
query_emb_key: question_emb
query_instruction: Given a question, retrieve passages that answer the question
chunks_df:
  class_parts:
  - Datahandle
  - ChunksDatahandle
  module_path: labtools.datahandle
  id: 3
  label: RAG_CHUNKS
  lab_name: injection_lab
  emb_pipe:
    id: 1
    label: NVEmbedPipeline
    lab_name: injection_lab
    class_parts:
    - EMBPipeline
    - NVEmbedPipeline
    module_path: beesup_llm.emb
    name_or_path: nvidia/NV-Embed-v2
    instruction: ''
  data_df:
    type: DataFrame
    filename: data_df.pkl
    n_rows: 3412
    columns: spo, s, p, o, source_name, attr_type, n_units, n_words, emb
    overwrite: false
limiters:
- class_parts:
  - RAGLimiter
  - NumLimiter
  module_path: beesup_llm.injection.rag
  limit: 100
- class_parts:
  - RAGLimiter
  - TokenLimiter
  module_path: beesup_llm.injection.rag
  limit: 1000
- class_parts:
  - RAGLimiter
  - KneeLimiter
  module_path: beesup_llm.injection.rag
  curve: convex
  direction: decreasing
