id: 1
label: LlamaPipeline
lab_name: injection_lab
class_parts:
- LLMPipeline
- LlamaPipeline
module_path: beesup_llm.model_pipelines
name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
generation_config:
  return_dict_in_generate: false
  max_time: 1200
  do_sample: false
  stop_strings: null
  max_new_tokens: 4096
  pad_token: <|begin_of_text|>
  pad_token_id: 128000
inference_tokenizer_config:
  padding: longest
  padding_side: left
  max_length: 8192
  pad_token: <|begin_of_text|>
  pad_token_id: 128000
training_tokenizer_config:
  padding: longest
  padding_side: right
  max_length: 8192
  pad_token: <|end_of_text|>
  pad_token_id: 128001
pipeline_args:
  return_full_text: false
  clean_up_tokenization_spaces: true
