id: 9
label: Taxomizer
lab_name: injection_lab
class_parts:
- Taxomizer
module_path: beesup_llm.injection.taxomizing
chunk_txt_template: '{p}: {o}'
chunk_txt_key: txt
chunk_emb_key: emb
linkage_args:
  method: ward
  optimal_ordering: false
dist_flattening_config:
  include_leaves: false
  use_kneepoint: false
  use_std: true
  std_factor: 1.1
ddist_flattening_config:
  include_leaves: false
  use_kneepoint: false
  use_std: true
  std_factor: 1.1
tree_info:
  bin_tree:
    num_inodes: 3411
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 8
    - 16
    - 30
    - 56
    - 96
    - 160
    - 227
    - 286
    - 316
    - 314
    - 284
    - 221
    - 172
    - 125
    - 103
    - 76
    - 62
    - 52
    - 50
    - 45
    - 42
    - 37
    - 39
    - 40
    - 39
    - 37
    - 32
    - 27
    - 24
    - 23
    - 23
    - 21
    - 20
    - 16
    - 12
    - 8
    - 7
    - 7
    - 6
    - 6
    - 5
    - 5
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 0
    - 2
    - 4
    - 16
    - 32
    - 93
    - 168
    - 256
    - 318
    - 344
    - 347
    - 270
    - 219
    - 147
    - 130
    - 90
    - 72
    - 54
    - 55
    - 48
    - 47
    - 35
    - 38
    - 41
    - 41
    - 42
    - 37
    - 30
    - 25
    - 23
    - 25
    - 22
    - 24
    - 20
    - 16
    - 9
    - 7
    - 8
    - 6
    - 7
    - 5
    - 6
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 4
    - 5
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 4
    - 2
    - 3
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    height: 121
    avg_depth: 20.1237
    width: 632
    dia: 231
    branching: 2.0
    avg_degree: 0.9999
    avg_balance: 4.3579
  dist_threshold: 0.5164165739396551
  dist_tree:
    num_inodes: 122
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 7
    - 11
    - 15
    - 22
    - 20
    - 21
    - 13
    - 3
    - 2
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 35
    - 482
    - 614
    - 332
    - 766
    - 340
    - 490
    - 257
    - 52
    - 22
    - 22
    height: 13
    avg_depth: 6.8053
    width: 786
    dia: 24
    branching: 29.1818
    avg_degree: 0.9997
    avg_balance: 0.0484
  ddist_threshold: 1.461172803130457
  ddist_tree_raw:
    num_inodes: 35
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 6
    - 9
    - 12
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 511
    - 949
    - 1004
    - 908
    - 40
    height: 7
    avg_depth: 4.7018
    width: 1016
    dia: 13
    branching: 101.2941
    avg_degree: 0.9997
    avg_balance: 0.0052
  ddist_tree_rec:
    num_inodes: 38
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 6
    - 10
    - 13
    - 2
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 511
    - 711
    - 1182
    - 796
    - 212
    height: 7
    avg_depth: 4.8383
    width: 1195
    dia: 13
    branching: 93.1622
    avg_degree: 0.9997
    avg_balance: 0.0043
llm_tree:
  filename: llm_tree.pkl
  type: dict
chunks_df:
  filename: chunks_df.pkl
  type: DataFrame
  columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label,
    txt
  n_rows: 3412
  overwrite: false
  id: 2
  label: ChunksDatahandle
  lab_name: injection_lab
  class_parts:
  - Datahandle
  - ChunksDatahandle
  module_path: labtools.datahandle
  remarks: 'emb = po_emb, excluded rows with p="Wissenschaftlicher Name" '
  drop_emb_duplicates: false
  emb_dh:
    id: 2
    label: EmbeddingDatahandle
    lab_name: injection_lab
    class_parts:
    - Datahandle
    - EmbeddingDatahandle
    module_path: labtools.datahandle
    emb_templates:
      s: '{s}'
      p: '{p}'
      o: '{o}'
      spo: '{s}


        {p}


        {o}'
      po: '{p}


        {o}'
      so: '{s}


        {o}'
    base_dh:
      id: 1
      label: wildbienen_database
      lab_name: injection_lab
      class_parts:
      - Datahandle
      - BaseDatahandle
      module_path: labtools.datahandle
    emb_pipe_config:
      id: 1
      label: NVEmbedPipeline
      lab_name: injection_lab
      class_parts:
      - EMBPipeline
      - NVEmbedPipeline
      module_path: beesup_llm.emb
      name_or_path: nvidia/NV-Embed-v2
      instruction: 'Instruct: Given a passage, retrieve a suitable header



        Passage:


        '
  data_df:
    filename: data_df.pkl
    type: DataFrame
    columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label
    n_rows: 3412
    overwrite: false
linkage_matrix:
  filename: linkage_matrix.pkl
  type: ndarray
  shape: (3411, 4)
  dtype: float64
bin_tree:
  filename: bin_tree.pkl
  type: Node
  size: 6823
  height: 121
dist_tree:
  filename: dist_tree.pkl
  type: Node
  size: 3534
  height: 13
ddist_tree:
  filename: ddist_tree.pkl
  type: Node
  size: 3450
  height: 7
emb_tree:
  filename: emb_tree.pkl
  type: Node
  size: 3450
  height: 7
