id: 5
label: InjectionExperiment
lab_name: injection_lab
class_parts:
- FinetuningExperiment
- InjectionExperiment
module_path: beesup_llm.injection.experiment
do_eval_base_model_rag: true
do_eval_lora_model_rag: true
done: false
do_eval_base_model: true
do_eval_lora_model: true
do_train: true
test_mode: false
lora_config:
  r: 32
  lora_alpha: 3
  use_rslora: true
  target_modules: all-linear
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_L
sft_config:
  num_train_epochs: 10
  output_dir: /home/fboehning/fboehning/injection_lab/FinetuningExperiment/InjectionExperiment/0005_InjectionExperiment
  auto_find_batch_size: true
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 1
  learning_rate: 0.0002
  optim: paged_adamw_8bit
  save_strategy: 'no'
  save_total_limit: 1
  eval_strategy: 'no'
  logging_strategy: steps
  logging_steps: 1
  logging_first_step: true
  do_train: true
  do_eval: false
  report_to: none
  max_seq_length: 4096
  packing: false
  prediction_loss_only: false
  remove_unused_columns: false
  seed: 42
evaluators:
- class_parts:
  - LLMEvaluator
  - InjectionEvaluator
  - MCQEvaluator
  module_path: beesup_llm.injection.evaluation
  id: 3
  label: BEES
  lab_name: injection_lab
  eval_df:
    filename: eval_df.pkl
    type: DataFrame
    columns: sidx, kidx, add_kidc, add_tidc, emb_col, question, choices, answer, question_emb
    n_rows: 1000
    overwrite: false
- class_parts:
  - LLMEvaluator
  - InjectionEvaluator
  - MCQEvaluator
  module_path: beesup_llm.injection.evaluation
  id: 4
  label: MMLU
  lab_name: injection_lab
  eval_df:
    filename: eval_df.pkl
    type: DataFrame
    columns: mmluidx, question, subject, choices, answer, question_emb
    n_rows: 1000
    overwrite: false
- class_parts:
  - LLMEvaluator
  - InjectionEvaluator
  - QDQEvaluator
  module_path: beesup_llm.injection.evaluation
  id: 1
  label: QDQEvaluator
  lab_name: injection_lab
  n_fewshots: 3
  eval_df:
    filename: eval_df.pkl
    type: DataFrame
    columns: question, target_attr, gold_items, question_emb
    n_rows: 30
    overwrite: false
- class_parts:
  - LLMEvaluator
  - InjectionEvaluator
  - FFQEvaluator
  module_path: beesup_llm.injection.evaluation
  id: 1
  label: BEES
  lab_name: injection_lab
  eval_df:
    filename: eval_df.pkl
    type: DataFrame
    columns: sidx, kidx, tidx, add_kidc, emb_col, question, answer, question_emb
    n_rows: 5
    overwrite: false
timestamp_start: 2025-03-25_14-14-28
lora_info:
  n_trainable_params: 83886080
  n_total_params: 8114147328
  p_trainable_params: 0.010338249554642546
  lora_scale: 0.5303300858899106
data_df:
  class_parts:
  - Datahandle
  - InjectionDatahandle
  module_path: labtools.datahandle
  id: 2
  label: InjectionDatahandle
  lab_name: injection_lab
  remarks: english system prompt, german query prompt
  use_taxonomy: false
  chunks_dh:
    id: 2
    label: ChunksDatahandle
    lab_name: injection_lab
    class_parts:
    - Datahandle
    - ChunksDatahandle
    module_path: labtools.datahandle
    drop_emb_duplicates: false
    emb_dh:
      id: 2
      label: EmbeddingDatahandle
      lab_name: injection_lab
      class_parts:
      - Datahandle
      - EmbeddingDatahandle
      module_path: labtools.datahandle
      emb_templates:
        s: '{s}'
        p: '{p}'
        o: '{o}'
        spo: '{s}


          {p}


          {o}'
        po: '{p}


          {o}'
        so: '{s}


          {o}'
      base_dh:
        id: 1
        label: wildbienen_database
        lab_name: injection_lab
        class_parts:
        - Datahandle
        - BaseDatahandle
        module_path: labtools.datahandle
      emb_pipe_config:
        id: 1
        label: NVEmbedPipeline
        lab_name: injection_lab
        class_parts:
        - EMBPipeline
        - NVEmbedPipeline
        module_path: beesup_llm.emb
        name_or_path: nvidia/NV-Embed-v2
        instruction: 'Instruct: Given a passage, retrieve a suitable header



          Passage:


          '
  data_df:
    filename: data_df.pkl
    type: DataFrame
    columns: kidx, tidx, prompt_messages, gold_message, split
    n_rows: 3412
    overwrite: false
llm_pipe:
  class_parts:
  - LLMPipeline
  - LlamaPipeline
  module_path: beesup_llm.llm
  label: LlamaPipeline
  lab_name: injection_lab
  name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
  generation_config:
    return_dict_in_generate: false
    max_time: 1200
    do_sample: false
    max_new_tokens: 4096
    pad_token: <|begin_of_text|>
    pad_token_id: 128000
  inference_tokenizer_config:
    padding: longest
    padding_side: left
    max_length: 8192
    pad_token: <|begin_of_text|>
    pad_token_id: 128000
  training_tokenizer_config:
    padding: longest
    padding_side: right
    max_length: 8192
    pad_token: <|end_of_text|>
    pad_token_id: 128001
  pipeline_args:
    return_full_text: false
    clean_up_tokenization_spaces: true
rag_pipe:
  class_parts:
  - RAGPipeline
  module_path: beesup_llm.rag
  label: RAGPipeline
  lab_name: injection_lab
  chunk_txt_key: spo
  chunk_emb_key: emb
  chunk_instruction: ''
  query_txt_key: question
  query_emb_key: question_emb
  query_instruction: Given a question, retrieve passages that answer the question
  limiters:
  - class_parts:
    - RAGLimiter
    - NumLimiter
    module_path: beesup_llm.rag
    limit: 100
  - class_parts:
    - RAGLimiter
    - TokenLimiter
    module_path: beesup_llm.rag
    limit: 1000
  - class_parts:
    - RAGLimiter
    - KneeLimiter
    module_path: beesup_llm.rag
    curve: convex
    direction: decreasing
  chunks_df:
    class_parts:
    - Datahandle
    - ChunksDatahandle
    module_path: labtools.datahandle
    id: 3
    label: RAG_CHUNKS
    lab_name: injection_lab
    remarks: 'emb = spo_emb, excluded rows with p="Wissenschaftlicher Name" '
    emb_pipe:
      id: 1
      label: NVEmbedPipeline
      lab_name: injection_lab
      class_parts:
      - EMBPipeline
      - NVEmbedPipeline
      module_path: beesup_llm.emb
      name_or_path: nvidia/NV-Embed-v2
      instruction: ''
    data_df:
      filename: data_df.pkl
      type: DataFrame
      columns: spo, s, p, o, source_name, attr_type, n_units, n_words, emb
      n_rows: 3412
      overwrite: false
