id: 32
label: Taxomizer
lab_name: injection_lab
class_parts:
- Taxomizer
module_path: beesup_llm.injection.taxomizing
chunk_txt_template: '{p}: {o}'
chunk_txt_key: txt
chunk_emb_key: emb
linkage_args:
  method: average
  optimal_ordering: false
dist_flattening_config:
  include_leaves: false
  use_kneepoint: false
  use_std: true
  std_factor: 0.8
ddist_flattening_config:
  include_leaves: false
  use_kneepoint: false
  use_std: true
  std_factor: 0.8
tree_info:
  bin_tree:
    num_inodes: 3411
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 8
    - 14
    - 20
    - 28
    - 38
    - 46
    - 50
    - 61
    - 62
    - 73
    - 73
    - 66
    - 69
    - 82
    - 80
    - 75
    - 78
    - 80
    - 75
    - 83
    - 78
    - 86
    - 83
    - 82
    - 71
    - 65
    - 57
    - 49
    - 45
    - 41
    - 36
    - 38
    - 41
    - 37
    - 39
    - 40
    - 37
    - 38
    - 35
    - 34
    - 28
    - 25
    - 26
    - 25
    - 25
    - 23
    - 22
    - 23
    - 27
    - 29
    - 27
    - 29
    - 27
    - 30
    - 23
    - 23
    - 18
    - 17
    - 13
    - 14
    - 12
    - 13
    - 11
    - 10
    - 10
    - 12
    - 9
    - 10
    - 10
    - 9
    - 9
    - 10
    - 11
    - 12
    - 16
    - 11
    - 13
    - 10
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 5
    - 5
    - 5
    - 5
    - 4
    - 4
    - 3
    - 3
    - 3
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 2
    - 8
    - 12
    - 18
    - 30
    - 42
    - 39
    - 60
    - 51
    - 73
    - 80
    - 63
    - 56
    - 84
    - 85
    - 72
    - 76
    - 85
    - 67
    - 88
    - 70
    - 89
    - 84
    - 93
    - 77
    - 73
    - 65
    - 53
    - 49
    - 46
    - 34
    - 35
    - 45
    - 35
    - 38
    - 43
    - 36
    - 41
    - 36
    - 40
    - 31
    - 24
    - 27
    - 25
    - 27
    - 24
    - 21
    - 19
    - 25
    - 31
    - 25
    - 31
    - 24
    - 37
    - 23
    - 28
    - 19
    - 21
    - 12
    - 16
    - 11
    - 15
    - 12
    - 10
    - 8
    - 15
    - 8
    - 10
    - 11
    - 9
    - 8
    - 9
    - 10
    - 8
    - 21
    - 9
    - 16
    - 12
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 8
    - 9
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 8
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    - 7
    - 5
    - 5
    - 5
    - 6
    - 4
    - 5
    - 3
    - 3
    - 4
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 3
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    height: 244
    avg_depth: 47.2097
    width: 172
    dia: 445
    branching: 2.0
    avg_degree: 0.9999
    avg_balance: 14.4881
  dist_threshold: 0.08417586311228092
  dist_tree:
    num_inodes: 1350
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 8
    - 11
    - 14
    - 20
    - 26
    - 28
    - 30
    - 36
    - 41
    - 45
    - 45
    - 41
    - 44
    - 58
    - 56
    - 48
    - 51
    - 55
    - 51
    - 55
    - 53
    - 57
    - 44
    - 45
    - 38
    - 34
    - 28
    - 25
    - 22
    - 15
    - 16
    - 18
    - 16
    - 15
    - 14
    - 12
    - 10
    - 14
    - 9
    - 11
    - 6
    - 8
    - 8
    - 8
    - 9
    - 5
    - 5
    - 6
    - 7
    - 10
    - 4
    - 4
    - 1
    - 1
    - 1
    - 1
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 30
    - 37
    - 12
    - 323
    - 172
    - 45
    - 90
    - 138
    - 284
    - 53
    - 107
    - 158
    - 138
    - 173
    - 170
    - 55
    - 54
    - 65
    - 56
    - 64
    - 75
    - 95
    - 68
    - 71
    - 67
    - 63
    - 35
    - 35
    - 44
    - 19
    - 26
    - 32
    - 42
    - 38
    - 27
    - 29
    - 12
    - 41
    - 11
    - 35
    - 5
    - 11
    - 11
    - 10
    - 58
    - 40
    - 21
    - 10
    - 4
    - 70
    - 4
    - 74
    - 1
    - 1
    - 1
    - 2
    height: 59
    avg_depth: 21.5187
    width: 349
    dia: 110
    branching: 3.5278
    avg_degree: 0.9998
    avg_balance: 1.3543
  ddist_threshold: 0.023659148427602316
  ddist_tree_raw:
    num_inodes: 897
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 9
    - 14
    - 18
    - 26
    - 31
    - 50
    - 46
    - 63
    - 90
    - 133
    - 153
    - 117
    - 62
    - 39
    - 19
    - 5
    - 10
    - 5
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 56
    - 20
    - 46
    - 359
    - 173
    - 133
    - 235
    - 504
    - 332
    - 253
    - 522
    - 374
    - 130
    - 92
    - 129
    - 15
    - 24
    - 15
    height: 21
    avg_depth: 11.9042
    width: 639
    dia: 36
    branching: 4.8058
    avg_degree: 0.9998
    avg_balance: 0.3203
  ddist_tree_rec:
    num_inodes: 1288
    num_leaves: 3412
    num_inodes_per_depth:
    - 2
    - 4
    - 9
    - 19
    - 23
    - 35
    - 39
    - 61
    - 72
    - 89
    - 120
    - 185
    - 226
    - 176
    - 110
    - 56
    - 31
    - 9
    - 11
    - 10
    - 0
    num_leaves_per_depth:
    - 0
    - 0
    - 0
    - 6
    - 58
    - 43
    - 51
    - 364
    - 191
    - 152
    - 517
    - 392
    - 174
    - 516
    - 461
    - 181
    - 105
    - 141
    - 14
    - 18
    - 28
    height: 21
    avg_depth: 12.2613
    width: 692
    dia: 36
    branching: 3.6496
    avg_degree: 0.9998
    avg_balance: 0.2104
chunks_df:
  filename: chunks_df.pkl
  type: DataFrame
  columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label,
    txt, node_id
  n_rows: 3412
  overwrite: false
  id: 2
  label: ChunksDatahandle
  lab_name: injection_lab
  class_parts:
  - Datahandle
  - ChunksDatahandle
  module_path: labtools.datahandle
  remarks: 'emb = po_emb, excluded rows with p="Wissenschaftlicher Name" '
  drop_emb_duplicates: false
  emb_dh:
    id: 2
    label: EmbeddingDatahandle
    lab_name: injection_lab
    class_parts:
    - Datahandle
    - EmbeddingDatahandle
    module_path: labtools.datahandle
    emb_templates:
      s: '{s}'
      p: '{p}'
      o: '{o}'
      spo: '{s}


        {p}


        {o}'
      po: '{p}


        {o}'
      so: '{s}


        {o}'
    base_dh:
      id: 1
      label: wildbienen_database
      lab_name: injection_lab
      class_parts:
      - Datahandle
      - BaseDatahandle
      module_path: labtools.datahandle
    emb_pipe_config:
      id: 1
      label: NVEmbedPipeline
      lab_name: injection_lab
      class_parts:
      - EMBPipeline
      - NVEmbedPipeline
      module_path: beesup_llm.emb
      name_or_path: nvidia/NV-Embed-v2
      instruction: 'Instruct: Given a passage, retrieve a suitable header



        Passage:


        '
  data_df:
    filename: data_df.pkl
    type: DataFrame
    columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label
    n_rows: 3412
    overwrite: false
linkage_matrix:
  filename: linkage_matrix.pkl
  type: ndarray
  shape: (3411, 4)
  dtype: float64
bin_tree:
  filename: bin_tree.pkl
  type: Node
  size: 6823
  height: 244
dist_tree:
  filename: dist_tree.pkl
  type: Node
  size: 4762
  height: 59
ddist_tree:
  filename: ddist_tree.pkl
  type: Node
  size: 4700
  height: 21
emb_tree:
  filename: emb_tree.pkl
  type: Node
  size: 4700
  height: 21
llm_tree:
  filename: llm_tree.pkl
  type: NoneType
