type: emb_model
id: 2
name: 0002_emb_model
path: /home/fboehning/fboehning/cluster_lab/emb_models/0002_emb_model
parent_dir_path: /home/fboehning/fboehning/cluster_lab/emb_models
parent_lab_path: /home/fboehning/fboehning/cluster_lab
name_or_path: jinaai/jina-embeddings-v3
task: classification
datetime_init: 2024-11-25 10:01:08.055526+01:00
trust_remote_code: true
use_flash_attn: false
dir_name: emb_models
lab_name: injection_lab
rel_path: injection_lab/emb_models/0002_emb_model
