framework_dirs:
- /home/fboehning/fboehning
module_path: /home/fboehning/fboehning/beesup_llm/experiment/injection_experiment.py
script_path: /home/fboehning/fboehning/beesup_llm/experiment/multirun_script.py
experiment_dirs:
- /home/fboehning/fboehning/injection_lab/injection_experiments/0006_injection_experiment
- /home/fboehning/fboehning/injection_lab/injection_experiments/0007_injection_experiment
