framework_dirs:
- /home/fboehning/fboehning
module_path: /home/fboehning/fboehning/beesup_llm/injection/injection_experiment.py
script_path: /home/fboehning/fboehning/beesup_llm/injection/multirun_script.py
experiment_dirs:
- /home/fboehning/fboehning/injection_lab/injection_experiments/0014_injection_experiment
