id: 4
label: emb_chunks
lab_name: injection_lab
class_parts:
- Datahandle
module_path: labtools.datahandle
remarks: 'emb = po_emb, excluded rows with p="Wissenschaftlicher Name" '
data_df:
  type: DataFrame
  filename: data_df.pkl
  n_rows: 3412
  columns: kidx, spo, s, p, o, source_name, attr_type, n_units, n_words, emb, label
  overwrite: false
