id: 2
label: raw_triples
lab_name: injection_lab
class_parts:
- Datahandle
module_path: labtools.datahandle
data_df:
  type: DataFrame
  filename: data_df.pkl
  n_rows: 3889
  columns: s, p, o, source_name, attr_type, n_units, n_words
  overwrite: false
